inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inventario/', include('list.urls')),
    path('admin/', admin.site.urls),
]

list/urls.py
from django.urls import path

from . import views

app_name = 'list'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('delete', views.delete, name='delete'),
    path('increase', views.increase, name='increase'),
    path('decrease', views.decrease, name='decrease'),
]

list/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255)
    quantity = models.IntegerField(default=5)

list/views.py
from django.shortcuts import render, redirect
from .models import Item


# Create your views here.
def index(request):
    items = Item.objects.all()
    context = {'items': items}

    return render(request, 'list/index.html', context)

def add(request):
    item = Item(name=request.POST['item-name'])
    item.save()
    return redirect('list:index')

def delete(request):
    item = Item.objects.get(pk=request.POST['delete-pk'])
    item.delete()
    return redirect('list:index')

def decrease(request):
    item = Item.objects.get(pk=request.POST['decrease-pk'])
    if item.quantity > 0:
        item.quantity -= 1
        item.save()
    return redirect('list:index')

def increase(request):
    item = Item.objects.get(pk=request.POST['increase-pk'])
    item.quantity += 1
    item.save()
    return redirect('list:index')

list/templates/list/index-bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventario</title>
</head>
<body>
{% load bootstrap4 %}
{% bootstrap_css %}
<div class="container">
    <h3 class="mt-2">Inventario CC4401</h3>

    <form class="form-inline" action="{% url 'list:add' %}" method="post">
        {% csrf_token %}
        <input type="text" class="form-control" name="item-name" placeholder="Nuevo producto">
        <button type="submit" class="btn btn-primary" value="Agregar">Agregar</button>
    </form>
    <hr>
    {% if items %}
        <ul>
            {% for item in items %}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <div class="col-3">
                            <button class="btn btn-danger" formaction="{% url 'list:delete' %}" type="submit"
                                    name="delete-pk" value="{{ item.id }}">Borrar
                            </button>
                            &nbsp;{{ item.name }}
                        </div>
                        <div class="col-3">
                            <button class="btn btn-light" formaction="{% url 'list:decrease' %}" type="submit"
                                    name="decrease-pk" value="{{ item.id }}">-
                            </button>
                            &nbsp;{{ item.quantity }}&nbsp;
                            <button class="btn btn-light" formaction="{% url 'list:increase' %}" type="submit"
                                    name="increase-pk" value="{{ item.id }}">+
                            </button>
                        </div>
                    </div>
                </form>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay items en el inventario</p>
    {% endif %}

</div>
</body>
</html>

list/templates/list/index-css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventario</title>
</head>
<body>
<style>
    div.item-lista {
        columns: 12em;
    }

    button {
        background-color: #6495ED;
        color: #FFFFFF
    }

    input[type=submit] {
        background-color: darkgreen;
        color: #FFFFFF;
    }
</style>
<h3>Inventario CC4401</h3>

<form action="{% url 'list:add' %}" method="post">
    {% csrf_token %}
    <input type="text" name="item-name" placeholder="Nuevo producto">
    <input type="submit" value="Agregar">
</form>
{% if items %}
    <ul>
        {% for item in items %}
            <form method="post">
                {% csrf_token %}
                <div class="item-lista">
                    <button formaction="{% url 'list:delete' %}" type="submit" name="delete-pk" value="{{ item.id }}">
                        Borrar
                    </button>
                    {{ item.name }}
                    <div>
                        <button formaction="{% url 'list:decrease' %}" type="submit" name="decrease-pk"
                                value="{{ item.id }}">-
                        </button>
                        {{ item.quantity }}
                        <button formaction="{% url 'list:increase' %}" type="submit" name="increase-pk"
                                value="{{ item.id }}">+
                        </button>
                    </div>
                </div>
            </form>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay items en el inventario</p>
{% endif %}
</body>
</html>

list/templates/list/index-material.html
{% extends 'materialize/materialize_base.html' %}
{% block content %}
    <div class="container">
        <h3>Inventario CC4401</h3>

        <form action="{% url 'list:add' %}" method="post">
            {% csrf_token %}
            <input type="text" name="item-name" placeholder="Nuevo producto">
            <button type="submit" class="btn waves-effect waves-light" value="Agregar">
                Agregar <i class="material-icons right">send</i>
            </button>
        </form>

        <div class="section">

            {% if items %}
                <ul>
                    {% for item in items %}
                        <div class="row">
                            <form method="post">
                                {% csrf_token %}
                                <div class="col s2">
                                    <button class="btn waves-effect waves-light btn-small red darken-2"
                                            formaction="{% url 'list:delete' %}" type="submit" name="delete-pk"
                                            value="{{ item.id }}">
                                        <i class="material-icons">delete</i>
                                    </button>
                                    &nbsp;{{ item.name }}
                                </div>
                                <button class="btn waves-effect waves-light btn-small blue lighten-4"
                                        formaction="{% url 'list:decrease' %}" type="submit" name="decrease-pk"
                                        value="{{ item.id }}">-
                                </button>
                                &nbsp;{{ item.quantity }}&nbsp;
                                <button class="btn waves-effect waves-light btn-small blue lighten-4"
                                        formaction="{% url 'list:increase' %}" type="submit" name="increase-pk"
                                        value="{{ item.id }}">+
                                </button>
                            </form>
                        </div>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No hay items en el inventario</p>
            {% endif %}
        </div>

    </div>

{% endblock %}

list/templates/list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventario</title>
</head>
<body>
<h3>Inventario CC4401</h3>

<form action="{% url 'list:add' %}" method="post">
    {% csrf_token %}
    <input type="text" name="item-name" placeholder="Nuevo producto">
    <input type="submit" value="Agregar">
</form>
{% if items %}
    <ul>
        {% for item in items %}
            <form method="post">
                {% csrf_token %}
                <button formaction="{% url 'list:delete' %}" type="submit" name="delete-pk" value="{{ item.id }}">
                    Borrar
                </button>
                {{ item.name }}
                <button formaction="{% url 'list:decrease' %}" type="submit" name="decrease-pk" value="{{ item.id }}">
                    -
                </button>
                {{ item.quantity }}
                <button formaction="{% url 'list:increase' %}" type="submit" name="increase-pk" value="{{ item.id }}">
                    +
                </button>
            </form>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay items en el inventario</p>
{% endif %}
</body>
</html>